### ISSUE TITLE
Settings aren't touch-friendly

### ISSUE THREAD

**Issue by lukaszciastko-spica** [argyleink/gui-challenges#14]
I really like your Settings example and the article that goes with it. Is there any chance you could update it and also try and make it touch-friendly?

I tested it on my iPhone, and the handles are very difficult to tap - one has to be very precise when trying to grab them as the touch area is the size of a handle. The same goes for checkboxes - you can tap on the text next to them but not within the area around them. Also, when you tap (either on the handle or the checkbox), the hover shadow doesn't go away.

Thank you!

**Comment by argyleink** [comment]
thanks for the report! what do you think of the PR which increases the size of the thumb and checkbox when the user is ~on a touch device (coarse hover or no hover)?
