### ISSUE TITLE
Tooltips: Tooltip is not conveyed to VoiceOver on MacOS on <a> elements

### ISSUE THREAD

**Issue by kimblim** [argyleink/gui-challenges#153]
When using keyboard navigation to tab to the `<a>` elements in the demo (the first eight instances), the content of the tooltip is not conveyed to VoiceOver. 

Tested on MacOS 12.6.1 using Safari 16.1 with VoiceOver enabled.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/254125/198223801-f8b2abee-b893-444b-a49a-2f0c9f706c70.png">

**Comment by argyleink** [comment]
I wonder where our tools have crossed paths? 

![image](https://user-images.githubusercontent.com/1134620/198411242-803df7ce-4275-452c-9e2d-3292fd910bdc.png)
[link](https://web.dev/building-a-tooltip-component/#:~:text=Screenshot%20of%20MacOS%20VoiceOver%20reading%20a%20link%20with%20a%20tooltip)

Maybe Chrome and Safari are differing in results here? I can test on my desktop when I'm in the office next 👍🏻

**Comment by kimblim** [comment]
I've just tried running it through Chrome, Edge and Firefox as well, and in those browsers VoiceOver do announce the tooltip — seems like a Safari-only issue.

**Comment by argyleink** [comment]
this world needs some AT interop efforts
