### ISSUE TITLE
Tooltip can be outside of window

### ISSUE THREAD

**Issue by fcrozatier** [argyleink/gui-challenges#155]
Hi !

For content on the side of the screen there is the possibility that the tooltip is partially outside of the window.

What about making sure the tooltip is always fully visible?

(Thanks for this series it's really great!)

**Comment by argyleink** [comment]
yes, i agree it's a bummer of this implementation that the tip can go outside the window. i'm waiting for CSS `anchor()` to help with that, as it'll provide a way to get that style with ease. So I was a bit lazy and didnt want to write JS that would mitigate the off screen presentation. 

glad you like the series, hopefully it's providing good insights into your own components and their ux! 🙂 

closing for now, but expect the tooltip to be revisited in a future episode, where i'll round out issues in accessibility and presentation 👍🏻
