### ISSUE TITLE
Did you mean startElement.style.animation = null ?

### ISSUE THREAD

**Issue by cold6lanket** [argyleink/gui-challenges#178]
https://github.com/argyleink/gui-challenges/blob/cfe9671a784838251d7f82439e6139afe5b9dd95/carousel/carousel.js#L220

**Comment by argyleink** [comment]
yep! 🙏🏻 
you want to PR a fix and get credit? or I can commit a fix otherwise?

**Comment by cold6lanket** [comment]
i want to fix it myself =)
