### ISSUE TITLE
Question: Why do you have `favicon.ico` in your example

### ISSUE THREAD

**Issue by junaga** [argyleink/gui-challenges#188]
Hi,

I wanted to ask, why did you include an `/favicon.ico` fallback in your [svg-favicon](https://github.com/argyleink/gui-challenges/tree/main/svg-favicon) challenge. Is it because [Safari does not support SVG](https://en.wikipedia.org/wiki/Favicon#Browser_implementation) or is there another reason?

If my browserlist excludes Safari, _Desktop App_, would it be OK to drop the `favicon.ico`? What do you think?

thank you

**Comment by junaga** [comment]
I read the Google webmaster documentation carefully. It is nowhere hinted that a `/favicon.ico`, _in the site root_, is a requirement.

**Comment by argyleink** [comment]
It's for progressive enhancement yep, [discussed here a bit](https://web.dev/building-an-adaptive-favicon/#overview). Do your thing!
