### ISSUE TITLE
Breadcrumbs and HTML5 Microdata

### ISSUE THREAD

**Issue by GianlucaGuarini** [argyleink/gui-challenges#44]
After watching this [great video](https://www.youtube.com/watch?v=kHL3gxAlvK8)

I was curious to understand how we can introduce [HTML5 microdata](https://developers.google.com/search/docs/data-types/breadcrumb) into the Demo HTML.

@argyleink Have you thought about that? Do you accept PRs?

**Comment by argyleink** [comment]
I do accept PRs! 🙂  

and no I hadnt thought of adding microdata to the markup, but def makes sense! the demo examples, at least one could show how to use microdata to enhance the markup. feel free to code up a little example and show me more about what you're thinking 👍🏻
