### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by filiptronicek** [argyleink/gui-challenges#56]
Hi Adam!
Very much enjoying the YouTube videos, they're so well done. I was wondering if I could integrate some of your CSS in an Open-Source project of mine, but I didn't find a license for the code, which AFAIK means you have the full copyright to the code and no one else can use it. If that's the case you want this code to be, that's fine by me, but I was curious anyway.

**Comment by argyleink** [comment]
apache license added 👍🏻 
please, go use my code in your open source project 🙂
