### ISSUE TITLE
CSS New Fectures

### ISSUE THREAD

**Issue by CICCIOSGAMINO** [argyleink/gui-challenges#57]
I like a lot the use of new CSS future features, but i think (personal opinion) that in some example they are use too heavy, for example in the split button css https://github.com/argyleink/gui-challenges/blob/main/split-buttons/split-button.css i'm experience a big fatigue to read the code ..... for example the use of long & chain remember me the pyramid of doom, or custom var of a custom var chain can be daunting to explore  .... I'm thinking are aspects to thinking of with the new CSS stardars down the road !

**Comment by argyleink** [comment]
I feel this yeah, it can easily become overwhelming looking at code, especially if it's using "new" features. Long `&` chains are definitely something to watch out for, and agree that my code might not be the best beginner friendly place to start. I'll try to adjust and see if I can mitigate some of these issues. Thanks for reporting!
