### ISSUE TITLE
Split Button: Replace physical absolute positioning with logical, like `inset-block-end` instead of `bottom`

### ISSUE THREAD

**Issue by benbender** [argyleink/gui-challenges#58]
Hey,

I wondered if the inconsistent use of `logical properties` is a bug or intentional? If it's intentional I would love to see an added comment about the why.

F.e.:
https://github.com/argyleink/gui-challenges/blob/86dddf0b9b886cd48013e36c4e4aefb1f7afcf1d/split-buttons/split-button.css#L170

**Comment by argyleink** [comment]
there are no logical absolute values yet, or transforms. afaik, they're different coordinate systems (aka they're not flow relative to the document). 

logical props get you real far, but not 100% completion yet. 

i'm open to suggestions!?
how would you have styled it?

**Comment by argyleink** [comment]
`inset-block-end` would be a better choice definitely! i always forget that. Thanks!

**Comment by benbender** [comment]
Yep, that's exactly what I thought :)

**Comment by benbender** [comment]
Upps, saw the title-change as pull. Not quite awake yet.
